version: '3.9'
services:
  bge_service:
    build:
      context: ./
      dockerfile: docker/Dockerfile
    container_name: public_embedding_api
    restart: always
    ports:
      - 8000:8000
    volumes:
      - ./models:/code/models 
    networks:
      - default
    environment:
      APP_HOST: ${APP_HOST:-0.0.0.0}
      APP_PORT: ${APP_PORT:-8000}
      API_KEY: ${API_KEY}

networks:
  default:
    driver: bridge

volumes:
  data:
    driver: local
