[project]
name = "swap-face-server"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10,<3.11"
dependencies = [
    "numpy==1.23.5",
    "opencv-python==4.8.1.78",
    "onnx>=1.17.0,<2.0.0",
    "insightface>=0.7.3,<0.8.0",
    "pillow<11.0.0",
    "torch==2.4.0",
    "torchvision==0.19.0",
    "onnxruntime>=1.20.1,<1.24; sys_platform == 'linux'",
    "onnxruntime>=1.20.1,<1.24; sys_platform == 'win32'",
    "onnxruntime-silicon==1.16.3; sys_platform == 'darwin'",
    #"onnxruntime-gpu>=1.20.1,<2.0.0; sys_platform == 'linux'",
    "protobuf==4.23.2",
    "tqdm==4.66.4",
    "fastapi>=0.115.6,<0.116.0",
    "pydantic>=2.10.4,<3.0.0",
    "uvicorn>=0.34.0,<0.35.0",
    "python-decouple>=3.8,<4.0.0",
    "python-multipart>=0.0.20,<0.0.21",
    "av>=14.0.1,<14.3",
    "moviepy<2.0.0",
    "mysql-connector-python>=9.1.0,<10.0.0",
    "pandas>=2.2.3,<3.0.0",
    "pytest>=8.3.4,<9.0.0",
    "pytest-asyncio>=0.25.0,<0.26.0",
    "websocket>=0.2.1,<0.3.0",
    "websockets>=15.0.1,<16.0.0",
]
