version: '3.9'
services:
  enhance_face_service:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    container_name: public_enhance_face_api
    restart: always
    ports:
      - 8000:8000
    networks:
      - default
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
              
networks:
  default:
    driver: bridge

volumes:
  data:
    driver: local
