version: '3.9'
services:
  bge_service:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    container_name: public_embedding_api
    restart: always
    ports:
      - 8000:8000
    networks:
      - default

networks:
  default:
    driver: bridge

volumes:
  data:
    driver: local
