[tool.poetry]
name = "public_api_server"
version = "0.1.0"
description = "Florence server"
authors = ["Walter Jin <jinshuhaicc@gmail.com>"]
license = "MIT License"
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "^3.12"
fastapi = "^0.115.4"
pandas = "^2.2.3"
numpy = "^1.23.0"
uvicorn = "^0.32.0"
pydantic = "^2.9.2"
jinja2 = "^3.1.4"
setuptools = "^75.5.0"
wheel = "^0.45.1"
Pillow = "^10.1.0"
torch = "^2.3.1"
torchaudio = "^2.3.1"
torchvision = "^0.18.1"
transformers = "^4.44.2"
librosa = "^0.9.0"
soundfile = "^0.12.1"
vector-quantize-pytorch = "^1.18.5"
vocos = "^0.1.0"
decord = "^0.6.0"
moviepy = "^2.1.2"
flash-attn = { version = "*", allow-prereleases = true }
python-decouple = "^3.8"
modelscope-studio = { url = "http://thunlp.oss-cn-qingdao.aliyuncs.com/multi_modal/never_delete/modelscope_studio-0.4.0.9-py3-none-any.whl" }
aiofiles = "^23.2.1"
onnxruntime = "^1.20.1"



[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
