version: '3.9'
services:
  owl_vit_service:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    container_name: public_owl_vit_api
    restart: always
    ports:
      - 8000:8000
    networks:
      - owl_vit
    #deploy:
    #  resources:
    #    reservations:
    #      devices:
    #        - driver: nvidia
    #          count: 1
    #          capabilities: [gpu]
              
networks:
  owl_vit:
    driver: bridge

volumes:
  data:
    driver: local
